declare module '@tabler/icons-react' {
  import { ComponentType, SVGProps } from 'react'

  export interface TablerIconProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    stroke?: number | string
  }

  export const IconAlertTriangle: ComponentType<TablerIconProps>
  export const IconArrowRight: ComponentType<TablerIconProps>
  export const IconBell: ComponentType<TablerIconProps>
  export const IconBrandGithub: ComponentType<TablerIconProps>
  export const IconTrendingDown: ComponentType<TablerIconProps>
  export const IconTrendingUp: ComponentType<TablerIconProps>
  export const IconBrandTwitter: ComponentType<TablerIconProps>
  export const IconCheck: ComponentType<TablerIconProps>
  export const IconChevronLeft: ComponentType<TablerIconProps>
  export const IconChevronRight: ComponentType<TablerIconProps>
  export const IconChevronsDown: ComponentType<TablerIconProps>
  export const IconCategory: ComponentType<TablerIconProps>
  export const IconUpload: ComponentType<TablerIconProps>
  export const IconArrowLeft: ComponentType<TablerIconProps>
  export const IconAlertCircle: ComponentType<TablerIconProps>
  export const IconCommand: ComponentType<TablerIconProps>
  export const IconFilter: ComponentType<TablerIconProps>
  export const IconCreditCard: ComponentType<TablerIconProps>
  export const IconDeviceLaptop: ComponentType<TablerIconProps>
  export const IconDotsVertical: ComponentType<TablerIconProps>
  export const IconGripVertical: ComponentType<TablerIconProps>
  export const IconFile: ComponentType<TablerIconProps>
  export const IconFileText: ComponentType<TablerIconProps>
  export const IconHelpCircle: ComponentType<TablerIconProps>
  export const IconLayoutDashboard: ComponentType<TablerIconProps>
  export const IconLayoutKanban: ComponentType<TablerIconProps>
  export const IconLoader2: ComponentType<TablerIconProps>
  export const IconLogin: ComponentType<TablerIconProps>
  export const IconLogout: ComponentType<TablerIconProps>
  export const IconMoon: ComponentType<TablerIconProps>
  export const IconPhoto: ComponentType<TablerIconProps>
  export const IconPhotoUp: ComponentType<TablerIconProps>
  export const IconPizza: ComponentType<TablerIconProps>
  export const IconRotate: ComponentType<TablerIconProps>
  export const IconSettings: ComponentType<TablerIconProps>
  export const IconShoppingBag: ComponentType<TablerIconProps>
  export const IconStar: ComponentType<TablerIconProps>
  export const IconSun: ComponentType<TablerIconProps>
  export const IconTrash: ComponentType<TablerIconProps>
  export const IconUser: ComponentType<TablerIconProps>
  export const IconUserCircle: ComponentType<TablerIconProps>
  export const IconUserEdit: ComponentType<TablerIconProps>
  export const IconUserX: ComponentType<TablerIconProps>
  export const IconX: ComponentType<TablerIconProps>
  export const IconBrowserCheck: ComponentType<TablerIconProps>
  export const IconChecklist: ComponentType<TablerIconProps>
  export const IconHelp: ComponentType<TablerIconProps>
  export const IconMessages: ComponentType<TablerIconProps>
  export const IconNotification: ComponentType<TablerIconProps>
  export const IconPackages: ComponentType<TablerIconProps>
  export const IconPalette: ComponentType<TablerIconProps>
  export const IconArrowsDiagonalMinimize2: ComponentType<TablerIconProps>
  export const IconTool: ComponentType<TablerIconProps>
  export const IconUserCog: ComponentType<TablerIconProps>
  export const IconUsers: ComponentType<TablerIconProps>
  export const IconUsersGroup: ComponentType<TablerIconProps>
  export const IconServer: ComponentType<TablerIconProps>
  export const IconLayoutGrid: ComponentType<TablerIconProps>
  export const IconLayoutColumns: ComponentType<TablerIconProps>
  export const IconAdjustmentsHorizontal: ComponentType<TablerIconProps>
  export const IconSortAscendingLetters: ComponentType<TablerIconProps>
  export const IconSortDescendingLetters: ComponentType<TablerIconProps>
  export const IconPaperclip: ComponentType<TablerIconProps>
  export const IconPhone: ComponentType<TablerIconProps>
  export const IconPhotoPlus: ComponentType<TablerIconProps>
  export const IconPlus: ComponentType<TablerIconProps>
  export const IconSearch: ComponentType<TablerIconProps>
  export const IconSend: ComponentType<TablerIconProps>
  export const IconVideo: ComponentType<TablerIconProps>
  export const IconBrightness: ComponentType<TablerIconProps>
  export const IconFolder: ComponentType<TablerIconProps>
  export const IconShare: ComponentType<TablerIconProps>
  export const IconDots: ComponentType<TablerIconProps>
  export const IconSparkles: ComponentType<TablerIconProps>
  export const IconCircleCheck: ComponentType<TablerIconProps>
  export const IconEdit: ComponentType<TablerIconProps>
  export const IconPlanet: ComponentType<TablerIconProps>
  export const IconArrowRightDashed: ComponentType<TablerIconProps>
  export const IconQuestionMark: ComponentType<TablerIconProps>
  export const IconRocket: ComponentType<TablerIconProps>
  export const IconEye: ComponentType<TablerIconProps>
  export const IconEyeOff: ComponentType<TablerIconProps>
  export const IconLoader: ComponentType<TablerIconProps>
  export const IconLeft: ComponentType<TablerIconProps>
  export const IconBrandDiscord: ComponentType<TablerIconProps>
  export const IconBrandDocker: ComponentType<TablerIconProps>
  export const IconBrandFigma: ComponentType<TablerIconProps>
  export const IconBrandGitlab: ComponentType<TablerIconProps>
  export const IconBrandGmail: ComponentType<TablerIconProps>
  export const IconBrandMedium: ComponentType<TablerIconProps>
  export const IconBrandNotion: ComponentType<TablerIconProps>
  export const IconBrandSkype: ComponentType<TablerIconProps>
  export const IconBrandSlack: ComponentType<TablerIconProps>
  export const IconBrandStripe: ComponentType<TablerIconProps>
  export const IconBrandTelegram: ComponentType<TablerIconProps>
  export const IconBrandTrello: ComponentType<TablerIconProps>
  export const IconBrandWhatsapp: ComponentType<TablerIconProps>
  export const IconBrandZoom: ComponentType<TablerIconProps>
  export const IconDownload: ComponentType<TablerIconProps>
  export const IconArrowDown: ComponentType<TablerIconProps>
  export const IconArrowUp: ComponentType<TablerIconProps>
  export const IconCircle: ComponentType<TablerIconProps>
  export const IconCircleX: ComponentType<TablerIconProps>
  export const IconExclamationCircle: ComponentType<TablerIconProps>
  export const IconStopwatch: ComponentType<TablerIconProps>
  export const IconMailPlus: ComponentType<TablerIconProps>
  export const IconUserPlus: ComponentType<TablerIconProps>
  export const IconCash: ComponentType<TablerIconProps>
  export const IconShield: ComponentType<TablerIconProps>
  export const IconUserShield: ComponentType<TablerIconProps>
}
